<?php
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Wed, 01/30/2008 - 01:22
 * View: tab_pubs
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   tab_pubs, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $field_publications_value --
 * $field_publications_value_label -- The assigned label for $field_publications_value
 * $field_publications_scholarsarch_url --
 * $field_publications_scholarsarch_url_label -- The assigned label for $field_publications_scholarsarch_url
 * $field_presentations_value --
 * $field_presentations_value_label -- The assigned label for $field_presentations_value
 * $field_presentations_scholarsarc_url --
 * $field_presentations_scholarsarc_url_label -- The assigned label for $field_presentations_scholarsarc_url
 * $field_materials_links_url --
 * $field_materials_links_url_label -- The assigned label for $field_materials_links_url
 * $field_materials_uploads_fid --
 * $field_materials_uploads_fid_label -- The assigned label for $field_materials_uploads_fid
 *
 * This function goes in your views-list-tab_pubs.tpl.php file
 */


 //now we add the stylesheet...
  //drupal_add_css(path_to_theme() .'/views-list-tab_pubs.css');

  ?>

  <?php if($field_publications_value) {
  print '<div class="view-label view-field-field-publications-value">';
  print $field_publications_value_label;
  print '</div><div class="view-field view-data-field-publications-value">';
  print $field_publications_value;
  print '</div>';
  }
if($field_publications_scholarsarch_url) {
  print '<div class="view-label view-field-field-publications-scholarsarch-url">';
  print $field_publications_scholarsarch_url_label;
  print '</div><div class="view-field view-data-field-publications-scholarsarch-url">';
  print $field_publications_scholarsarch_url;
  print '</div>';
  }
if($field_presentations_value) {
 print '<div class="view-label view-field-field-presentations-value">';
 print $field_presentations_value_label;
 print '</div><div class="view-field view-data-field-presentations-value">';
 print $field_presentations_value;
  print '</div>';
  }
  if($field_presentations_scholarsarc_url) {
print '<div class="view-label view-field-field-presentations-scholarsarc-url">';
print $field_presentations_scholarsarc_url_label;
print '</div><div class="view-field view-data-field-presentations-scholarsarc-url">';
print $field_presentations_scholarsarc_url;
 print '</div>';
  }
if($field_materials_links_url != '<div class="field-item"></div>') {
print '<div class="view-label view-field-field-materials-links-url">';
  print $field_materials_links_url_label;
print '</div><div class="view-field view-data-field-materials-links-url">';
  print $field_materials_links_url;
print '</div>';
}
if($field_materials_uploads_fid != '<div class="field-item"></div>') {
print '<div class="view-label view-field-field-materials-uploads-fid">';
print $field_materials_uploads_fid_label;
print '</div><div class="view-field view-data-field-materials-uploads-fid">';
  print $field_materials_uploads_fid;
print '</div>';
}


