<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Wed, 11/05/2008 - 10:22am
 * View: Subject_Specialist_by_name
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   Subject_Specialist_by_name, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $name -- This will display the author of the node.
 * $name_label -- The assigned label for $name
 * $field_subjects_value -- 
 * $field_subjects_value_label -- The assigned label for $field_subjects_value
 *
 * This function goes in your views-list-Subject_Specialist_by_name.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-Subject_Specialist_by_name.css');
  
  ?>

<div class="view-field view-data-name">
  <table><tr><td><?php print $name.": "?></td><td><?php print $field_subjects_value?></td></tr></table>
</div>
