<?php
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Tue, 01/29/2008 - 21:00
 * View: tab_committees
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   tab_committees, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $field_my_library_committees_nid --
 * $field_my_library_committees_nid_label -- The assigned label for $field_my_library_committees_nid
 * $field_professional_associations_value --
 * $field_professional_associations_value_label -- The assigned label for $field_professional_associations_value
 * $field_university_service_value --
 * $field_university_service_value_label -- The assigned label for $field_university_service_value
 *
 * This function goes in your views-list-tab_committees.tpl.php file
 */


 //now we add the stylesheet...
  //drupal_add_css(path_to_theme() .'/views-list-tab_committees.css');

  ?>

  <?php
  if($field_my_library_committees_nid != '<div class="field-item"></div>') {
  print '<div class="view-label view-field-field-my-library-committees-nid">';
  print $field_my_library_committees_nid_label;
  print '</div><div class="view-field view-data-field-my-library-committees-nid">';
  print $field_my_library_committees_nid;
  print'</div>';
  }
if($field_professional_associations_value) {
  print '<div class="view-label view-field-field-professional-associations-value">';
  print $field_professional_associations_value_label;
  print '</div><div class="view-field view-data-field-professional-associations-value">';
  print $field_professional_associations_value;
  print'</div>';
}

if ($field_university_service_value) {
  print '<div class="view-label view-field-field-university-service-value">';
  print $field_university_service_value_label;
  print '</div><div class="view-field view-data-field-university-service-value">';
  print $field_university_service_value;
  print'</div>';
}
?>