<div class="mystuff">
<a href="http://oasis.oregonstate.edu/screens/accesrec.html">My Library Account</a>
<div id="m0" class="mhead noline">
  <img src="/images/closed.gif" alt="click to open" title="click to open" id="i0" />
  <a>Change My View</a>
</div>
<div class="submenu noline" id="s0">
  <a class="view" id="v1">Graduate</a>
  <a class="view" id="v2">Faculty</a>
  <a class="view" id="v3" href="/offcampus/bridge.html">ECampus</a>
  <a class="view" id="v0">General/Undergrad</a>
</div>
</div>

<div class="findit">
<div id="m1" class="mhead">
  <img src="/images/closed.gif" alt="click to open" title="click to open" id="i1" />
  <a href="/books_and_articles.html">Find Books &amp; Articles</a>
</div>
<div class="submenu" id="s1">
  <a href="/books.html">Find Books</a>
  <a href="/articles.html">Find Articles</a>
  <a href="/libraryfind.html">LibraryFind</a>
  <a href="http://osulibrary.oregonstate.edu/ill/">Interlibrary Loan</a>
</div>
<div id="m2" class="mhead">
  <img src="/images/closed.gif" alt="click to open" title="click to open" id="i2" />
  <a href="/other_resources.html">Find Other Resources</a>
</div>
<div class="submenu" id="s2">
  <a href="http://osulibrary.oregonstate.edu/research/govpubs.html">Government Documents</a>
  <a href="http://osulibrary.oregonstate.edu/research/guides/maps/maproom.htm">Maps</a>
  <a href="http://osulibrary.orst.edu/libraries_and_collections/art/">Northwest Art Exhibit</a>
  <a href="http://ir.library.oregonstate.edu/dspace/index.jsp">ScholarsArchive@OSU</a>
  <a href="http://osulibrary.oregonstate.edu/specialcollections/">Special Collections</a>
  <a href="http://osulibrary.oregonstate.edu/digitalcollections/">Unique at OSU</a>
  <a href="http://osulibrary.oregonstate.edu/archives/">University Archives</a>
  <a href="/circ/multimedia.html">Audio &amp; Video</a>
  <a href="http://osulibrary.oregonstate.edu/research/magazines_and_newspapers.html">Magazines &amp; Newspapers</a>
</div>
<a href="http://osulibrary.oregonstate.edu/research/subject_directory.html" class="noline">Browse By Subject</a>
</div>

<div class="thelib">
<div id="m3" class="mhead">
  <img src="/images/closed.gif" alt="click to open" title="click to open" id="i3" />
  <a href="/thelibrary.html">Using the Library</a>
</div>
<div class="submenu" id="s3">
  <a href="http://osulibrary.oregonstate.edu/hours/">Hours</a>
  <a href="http://osulibrary.oregonstate.edu/policies/">Policies</a>
  <a href="/locations/index.html">Floormaps</a>
  <a href="http://osulibrary.oregonstate.edu/circ/">Borrowing &amp; Requesting</a>
  <a href="http://osulibrary.oregonstate.edu/circ/rooms_lockers_laptops.html">Study Rooms, Lockers, Laptops</a>
  <a href="http://osulibrary.oregonstate.edu/copy/">Copy Services</a>
  <a href="http://osulibrary.oregonstate.edu/reserves/">Look up Course Reserves</a>
  <a href="http://oregonstate.edu/is/mediaservices/sms/">Multimedia Services</a>
<a href="http://osulibrary.oregonstate.edu/research/guides/perdis.htm">Disability Services</a>
</div>
<div id="m4" class="mhead">
  <img src="/images/closed.gif" alt="click to open" title="click to open" id="i4" />
  <a href="/learning_spaces.html">Learning Spaces</a>
</div>
<div class="submenu" id="s4">
  <a href="http://osulibrary.oregonstate.edu/computing">Learning Commons</a>
  <a href="http://osulibrary.oregonstate.edu/clc/">Collaborative Learning</a>
  <a href="http://osulibrary.oregonstate.edu/circ/rooms.html">Study Rooms</a>
  <a href="http://osulibrary.oregonstate.edu/instruction/classrooms.html">Classrooms</a>
</div>
<a href="http://osulibrary.oregonstate.edu/archives/">University Archives</a>
<a href="http://osulibrary.oregonstate.edu/specialcollections/">Special Collections</a>
<div id="m5" class="mhead noline">
  <img src="/images/closed.gif" alt="click to open" title="click to open" id="i5" />
  <a href="/about.html">About OSU Libraries</a>
</div>
<div class="submenu noline" id="s5">
  <a href="/valley.html">Valley Library</a>
  <a href="http://osulibrary.oregonstate.edu/cascades">Cascades Campus Library</a>
  <a href="http://osulibrary.oregonstate.edu/guin/">Guin Library</a>
  <a href="http://osulibrary.oregonstate.edu/new/whatsnew.htm">What's New</a>
  <a href="/locations/findus.html">Directories</a>
  <a href="http://osulibrary.oregonstate.edu/giving/">Giving to OSU Libraries</a>
  <a href="http://oregonstate.edu/dept/press/">OSU Press</a>
  <a href="http://osulibrary.oregonstate.edu/administration/">Library Administration</a>
  <a href="http://osulibrary.oregonstate.edu/intranet/">Library Intranet</a>
</div>
</div>

<div class="gethelp">
  <a href="http://osulibrary.oregonstate.edu/faq.html">How Do I...?</a>
  <a href="http://osulibrary.oregonstate.edu/reference/">Ask a Librarian</a>
  <a href="http://osulibrary.oregonstate.edu/instruction/tutorials/tutorials.html">Demos and Guides</a>
  <a href="http://osulibrary.oregonstate.edu/staff/sublist.html">Get Help with a Subject</a>
  <a href="http://ica.library.oregonstate.edu/Course_Assignment_Pages">Get Help with a Class</a>
  <a href="http://osulibrary.oregonstate.edu/comments/comments.html">Comments &amp; Suggestions</a>
</div>
<a href="http://osulibrary.oregonstate.edu">Home</a>
