<?php
/**
 * @file
 * OSUL Search
 * Creates a search form, configurable under the block menu.
 */

/**
 * Implements hook_block_info().
 */
function osul_search_block_info() {
  $blocks = array(
    'osul_search' => array(
      'info' => t('OSUL Search: Library'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
    'course_reserves' => array(
      'info' => t('OSUL Search: Course Reserves'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
    'web_site' => array(
      'info' => t('OSUL Search: Website'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function osul_search_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'osul_search':
      $block['subject'] = t(variable_get('osul_search_title', NULL));
      $block['content'] = drupal_get_form('osul_search_library_form');
      break;
    case 'course_reserves':
      $block['subject'] = t(variable_get('osul_course_reserves_title', NULL));
      $block['content'] = drupal_get_form('osul_search_reserves_form');
      break;
    case 'web_site':
      $block['subject'] = t(variable_get('osul_website_title', NULL));
      $block['content'] = drupal_get_form('google_appliance_block_form');
      break;
  }
  return $block;
}

/**
 * Implements hook_block_configure().
 */
function osul_search_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'osul_search':
      $form = osul_search_library_config_form();
      break;
    case 'course_reserves':
      $form = osul_search_reserves_config_form();
      break;
  }
  return $form;
}

/**
 * Creates elements for the admin config form of the 1Search form.
 * @return array
 */
function osul_search_library_config_form() {
  $form['osul_search_library_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Primo\'s Url and Port'),
    '#default_value' => variable_get('osul_search_library_url', 'http://alliance-pubsb.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do'),
    '#required' => TRUE,
    '#description' => t('Full URL to Primo\'s dlSearch.do. Example: http://alliance-pubsb.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do'),
  );
  $form['osul_search_library_institution_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Institution Code'),
    '#default_value' => variable_get('osul_search_library_institution_code', 'OSU'),
    '#required' => TRUE,
    '#description' => t('This needs to be your Primo Institution Code. Example: OSU'),
  );
  $form['osul_search_library_view_code'] = array(
    '#type' => 'textfield',
    '#title' => t('View code.'),
    '#default_value' => variable_get('osul_search_library_view_code', 'OSU'),
    '#required' => TRUE,
    '#description' => t('View Code for dlSearch to use. Example: OSU'),
  );
  $form['osul_search_library_search_scope'] = array(
    '#type' => 'textfield',
    '#title' => t('Search Scope'),
    '#default_value' => variable_get('osul_search_library_search_scope', 'everything'),
    '#required' => TRUE,
    '#description' => t('The scope to be used for this search. Example: everything'),
  );
  $form['osul_search_library_placeholder'] = array(
    '#type' => 'textfield',
    '#title' => t('Search placeholder for the search field'),
    '#default_value' => variable_get('osul_search_library_placeholder', 'Search OSU Libraries'),
    '#description' => t('The words that will be added to the when the field is blank.'),
  );
  $form['osul_search_library_advanced_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Advanced Search link'),
    '#default_value' => variable_get('osul_search_library_advanced_url', 'http://alliance-pubsb.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&vid=OSU'),
    '#required' => TRUE,
    '#description' => t('Full URL to Primo\'s Library Catalog Advanced Search tab.'),
    '#maxlength' => 200,
  );
  $form['osul_search_library_tips_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Search Tips link'),
    '#default_value' => variable_get('osul_search_library_tips_url', ''),
    '#required' => TRUE,
    '#description' => t('Full URL to search tips page.'),
  );
  return $form;
}

/**
 * Creates elements for the admin config form for the Course Reserves search form.
 * @return array
 */
function osul_search_reserves_config_form() {
  $form['osul_search_reserves_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Primo Search URL'),
    '#default_value' => variable_get('osul_search_reserves_url', 'http://alliance-pubsb.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do'),
    '#required' => TRUE,
    '#description' => t('Full URL to Primo\'s dlSearch.do. Example: http://alliance-pubsb.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do'),
  );
  $form['osul_search_reserves_institution_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Institution Code'),
    '#default_value' => variable_get('osul_search_reserves_institution_code', 'OSU'),
    '#required' => TRUE,
    '#description' => t('Primo Institution Code. Example: OSU'),
  );
  $form['osul_search_reserves_view_code'] = array(
    '#type' => 'textfield',
    '#title' => t('View code.'),
    '#default_value' => variable_get('osul_search_reserves_view_code', 'OSU'),
    '#required' => TRUE,
    '#description' => t('View Code for dlSearch to use. Example: OSU'),
  );
  $form['osul_search_reserves_search_scope'] = array(
    '#type' => 'textfield',
    '#title' => t('Search Scope'),
    '#default_value' => variable_get('osul_search_reserves_search_scope', 'osu_cr'),
    '#required' => TRUE,
    '#description' => t('The scope to be used for this search. Example: osu_cr'),
  );
  $form['osul_search_reserves_placeholder'] = array(
    '#type' => 'textfield',
    '#title' => t('Placeholder text for the search field'),
    '#default_value' => variable_get('osul_search_reserves_placeholder', 'Search OSU Libraries'),
    '#description' => t('The words that will be displayed the when the field is blank.'),
  );
  $form['osul_search_reserves_advanced_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Advanced Search link'),
    '#default_value' => variable_get('osul_search_reserves_advanced_url', 'http://alliance-pubsb.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&vid=OSU&tab=cr_tab'),
    '#required' => TRUE,
    '#description' => t('Full URL to Primo\'s Course Reserve Advanced search tab.'),
    '#maxlength' => 200,
  );
  $form['osul_search_reserves_tips_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Search Tips link'),
    '#default_value' => variable_get('osul_search_reserves_tips_url', ''),
    '#required' => TRUE,
    '#description' => t('Full URL to search tips page.'),
  );
  return $form;
}


/**
 * Implements hook_block_save().
 */
function osul_search_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'osul_search':
      variable_set('osul_search_library_search_scope', $edit['osul_search_library_search_scope']);
      variable_set('osul_search_library_view_code', $edit['osul_search_library_view_code']);
      variable_set('osul_search_library_institution_code', $edit['osul_search_library_institution_code']);
      variable_set('osul_search_library_url', $edit['osul_search_library_url']);
      variable_set('osul_search_library_placeholder', $edit['osul_search_library_placeholder']);
      variable_set('osul_search_library_advanced_url', $edit['osul_search_library_advanced_url']);
      variable_set('osul_search_library_tips_url', $edit['osul_search_library_tips_url']);
      break;
    case 'course_reserves':
      variable_set('osul_search_reserves_search_scope', $edit['osul_search_reserves_search_scope']);
      variable_set('osul_search_reserves_view_code', $edit['osul_search_reserves_view_code']);
      variable_set('osul_search_reserves_institution_code', $edit['osul_search_reserves_institution_code']);
      variable_set('osul_search_reserves_url', $edit['osul_search_reserves_url']);
      variable_set('osul_search_reserves_placeholder', $edit['osul_search_reserves_placeholder']);
      variable_set('osul_search_reserves_advanced_url', $edit['osul_search_reserves_advanced_url']);
      variable_set('osul_search_reserves_tips_url', $edit['osul_search_reserves_tips_url']);
      break;
    case 'web_site':
      break;
  }
}

/**
 * Defines the components of the 1Search form.
 * @param $form
 * @param $form_state
 * @return mixed
 */
function osul_search_library_form($form, &$form_state) {
  $module_path = drupal_get_path('module', 'osul_search');
  $form['#attributes'] = array(
    'class' => array('osul-search-form'),
  );
  $form['query_temp'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'id' => 'query_temp',
      'placeholder' => variable_get('osul_search_library_placeholder', NULL),
      'class' => array('search'),
      'size' => 100,
      'maxlength' => 128,
    ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
    '#attributes' => array(
      'alt' => 'search',
    ),
  );
  $form['search_links'] = array(
    '#markup' => '<div class="search-links">'
      . l('Advanced Search', variable_get('osul_search_library_advanced_url', NULL))
      . l('Search tips', variable_get('osul_search_library_tips_url', NULL)) . '</div>',
  );
  $form['search_scope'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('osul_search_library_search_scope', NULL),
    '#attributes' => array(
      'name' => 'search_scope',
    ),
  );
  $form['institution'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('osul_search_library_institution_code', NULL),
    '#attributes' => array(
      'name' => 'institution',
    ),
  );
  $form['vid'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('osul_search_library_view_code', NULL),
    '#attributes' => array(
      'name' => 'vid',
    ),
  );
  $form['group'] = array(
    '#type' => 'hidden',
    '#value' => 'GUEST',
    '#attributes' => array(
      'name' => 'group',
    ),
  );
  $form['onCampus'] = array(
    '#type' => 'hidden',
    '#value' => 'true',
    '#attributes' => array(
      'name' => 'onCampus',
    ),
  );
  $form['displayMode'] = array(
    '#type' => 'hidden',
    '#value' => 'full',
    '#attributes' => array(
      'name' => 'displayMode',
    ),
  );
  $form['query'] = array(
    '#type' => 'hidden',
    '#attributes' => array(
      'name' => 'query',
    ),
  );
  $form['tab'] = array(
    '#type' => 'hidden',
    '#value' => 'default_tab',
    '#attributes' => array(
      'name' => 'tab',
    ),
  );
  $form['#attached'] = array(
    'css' => array($module_path . '/css/osul_search.css'),
  );
  return $form;
}

/**
 * Implements hook_submit().
 * For the 1Search form: modifies the form data as needed before sending on to Primo.
 * @param $form
 * @param $form_state
 */
function osul_search_library_form_submit($form, &$form_state) {
  $query = osul_search_build_query_array($form_state['values']);
  $query['query'] = 'any,contains,' . $form_state['values']['query_temp'];
  drupal_goto(variable_get('osul_search_library_url', NULL), array('query' => $query));
}

/**
 * Defines the components of the Course Reserves search form.
 * @param $form
 * @param $form_state
 * @return mixed
 */
function osul_search_reserves_form($form, &$form_state) {
  $module_path = drupal_get_path('module', 'osul_search');
  $form['#attributes'] = array(
    'class' => array('osul-search-form'),
  );
  $form['query_temp_reserve'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'id' => 'query_temp_reserve',
      'placeholder' => variable_get('osul_search_reserves_placeholder', NULL),
      'class' => array('search'),
      'size' => 100,
      'maxlength' => 128,
    ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
    '#attributes' => array(
      'alt' => 'search',
    ),
  );
  $form['search_links'] = array(
    '#markup' => '<div class="search-links">'
      . l('Advanced Search', variable_get('osul_search_reserves_advanced_url', NULL))
      . l('Search tips', variable_get('osul_search_reserves_tips_url', NULL)) . '</div>',
  );
  $form['search_scope'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('osul_search_reserves_search_scope', NULL),
    '#attributes' => array(
      'name' => 'search_scope',
    ),
  );
  $form['institution'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('osul_search_reserves_institution_code', NULL),
    '#attributes' => array(
      'name' => 'institution',
    ),
  );
  $form['vid'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('osul_search_reserves_view_code', NULL),
    '#attributes' => array(
      'name' => 'vid',
    ),
  );
  $form['group'] = array(
    '#type' => 'hidden',
    '#value' => 'GUEST',
    '#attributes' => array(
      'name' => 'group',
    ),
  );
  $form['onCampus'] = array(
    '#type' => 'hidden',
    '#value' => 'true',
    '#attributes' => array(
      'name' => 'onCampus',
    ),
  );
  $form['displayMode'] = array(
    '#type' => 'hidden',
    '#value' => 'full',
    '#attributes' => array(
      'name' => 'displayMode',
    ),
  );
  $form['displayField'] = array(
    '#type' => 'hidden',
    '#value' => 'all',
    '#attributes' => array(
      'name' => 'displayField',
    ),
  );
  $form['highlight'] = array(
    '#type' => 'hidden',
    '#value' => 'true',
    '#attributes' => array(
      'name' => 'highlight',
    ),
  );
  $form['mode'] = array(
    '#type' => 'hidden',
    '#value' => 'Basic',
    '#attributes' => array(
      'name' => 'mode',
    ),
  );
  $form['tab'] = array(
    '#type' => 'hidden',
    '#value' => 'cr_tab',
    '#attributes' => array(
      'name' => 'tab',
    ),
  );
  $form['#attached'] = array(
    'css' => array($module_path . '/css/osul_search.css'),
  );
  return $form;
}

/**
 * Helper function to create query string for Primo, leaving out unneeded fields.
 * @param $form_values
 * @return array
 */
function osul_search_build_query_array($form_values) {
  $query = array();
  // Omit the form_ fields and remove _reserve from the field names if present for submission to Primo
  foreach ($form_values as $key => $value) {
    if ('form_' != substr($key, 0, 5)) {
      $res = strpos($key, '_reserve');
      if (FALSE !== $res) {
        $key = substr($key, 0, $res);
      }
      $query[$key] = $value;
    }
  }
  return $query;
}

/**
 * Implements hook_submit().
 * For the Course Reserves form: modifies the form data as needed before sending on to Primo.
 * @param $form
 * @param $form_state
 */
function osul_search_reserves_form_submit($form, &$form_state) {
  $query = osul_search_build_query_array($form_state['values']);
  $query['query'] = 'any,contains,' . $form_state['values']['query_temp_reserve'];
  drupal_goto(variable_get('osul_search_reserves_url', NULL), array('query' => $query));
}
